# Generated by Django 4.2.1 on 2023-05-15 15:25

from django.db import migrations, models
import django.db.models.deletion
import tasks.models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_task_subject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'asignatura', 'verbose_name_plural': 'asignaturas'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'tarea', 'verbose_name_plural': 'tareas'},
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, default=None, null=True, validators=[tasks.models.past_date], verbose_name='fecha de entrega'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('L', 'Prioridad baja'), ('N', 'Prioridad media'), ('H', 'Prioridad alta')], default='N', max_length=1, verbose_name='prioridad'),
        ),
        migrations.AlterField(
            model_name='task',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='tasks.subject', verbose_name='asignatura'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=250, unique=True, verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='task',
            name='urgent',
            field=models.BooleanField(default=False, verbose_name='urgente'),
        ),
    ]
